modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory

[[mods]] #mandatory
modId="all_the_features" #mandatory
logoFile=""
version="${version}" #mandatory
displayName="All The Features" #mandatory
displayURL=""
authors="TelepathicGrunt"
credits="Special thanks to all the Forge tutorials and debugging help from other modders to help make this mod possible!"
description='''Av'''